version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./db.json:/usr/src/cart_api/db.json 
      - ./logs/json-server:/usr/src/cart_api/logs

networks:
  app-network:
    driver: bridge
